version: '3.1'

services:
  web:
    build: .
    restart: always
    environment:
      - SERVER_PORT=80
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://root:CHANGEME@mongo:27017
      - MONGO_DBNAME=production
      - COOKIE_SECRET=CHANGEME
      - RATE_LIMIT=20
      - ADMIN_NAME=Example Admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=CHANGEME
    ports:
      - "80:80"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: CHANGEME
      MONGO_INITDB_DATABASE: production
    volumes:
      - mongodata:/data/db
  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
volumes:
  mongodata:
  redisdata:
